export const projects = [
  {
    github: "https://github.com/Raja-Simform/IndiaPost",
    live: "https://india-post-gy2ty90a5-raja-jhas-projects.vercel.app/",
    title: "India Post App",
    desc: "The Postal PIN Code API provides detailed information about post offices across India. You can search by postal PIN code or branch name to get data such as branch type, delivery status, district, state, and more.",
    technology: ["REACT", "TYPESCRIPT", "TAILWIND"],
  },
  {
    github: "https://github.com/Raja-Simform/CustomHooks",
    live: "https://custom-hooks-jade.vercel.app/",
    title: "Custom Hooks",
    desc: "A collection of reusable custom React hooks built with TypeScript and styled using Tailwind CSS, designed to simplify state management and enhance code reusability across React applications.",
    technology: ["REACT", "TYPESCRIPT", "TAILWIND"],
  },
  {
    github: "https://github.com/Raja-Simform/Atomix",
    live: "",
    title: "Atomix-ComponentLibrary",
    desc: "A collection of reusable custom React hooks built with TypeScript and styled using Tailwind CSS, designed to simplify state management and enhance code reusability across React applications.",
    technology: ["REACT", "TYPESCRIPT", "TAILWIND"],
  },
  {
    github: "https://github.com/Raja-Simform/React-Paint-App/tree/dev",
    live: "https://react-paint-app-rosy.vercel.app/",
    title: "Paint App",
    desc: "An interactive paint application built with React and TypeScript, featuring a user-friendly interface styled with Tailwind CSS that allows drawing, color selection, and canvas manipulation.",
    technology: ["REACT", "TYPESCRIPT", "TAILWIND"],
  },
  {
    github: "https://github.com/Raja-Simform/Portfolio-project",
    live: "https://portfolio-project-git-dev-raja-jhas-projects.vercel.app/?_vercel_share=8X1um13WtZzQd8aVt2avuKNTJQeGPVtF",
    title: "Portfolio App",
    desc: "A modern and responsive portfolio application built with React and TypeScript, showcasing projects and skills with styled components for a sleek and maintainable design.",
    technology: ["REACT", "TYPESCRIPT", "STYLE COMPONENTS"],
  },
  {
    github: "https://github.com/Raja-Simform/Coin-Voyage",
    live: "https://grand-pudding-9f6346.netlify.app/",
    title: "A Coin-Voyage Game",
    desc: "An interactive coin-collecting game built using TypeScript and MVC architecture, featuring smooth gameplay and responsive design.",
    technology: ["HTML", "CSS", "TYPESCRIPT", "MVC"],
  },
  {
    github: "https://github.com/Raja-Simform/React-Paint-App",
    live: "https://react-paint-app-rosy.vercel.app/",
    title: "A React Paint App",
    desc: "A creative painting application developed with React and TypeScript, allowing users to draw freely with customizable brushes and colors.",
    technology: ["REACT", "CSS", "TYPESCRIPT"],
  },
  {
    github: "https://github.com/Raja-Simform/Tic-Tac-Toe",
    live: "https://clever-youtiao-cf4830.netlify.app/",
    title: "Tic-Tac-Toe Game",
    desc: "A classic Tic-Tac-Toe game implemented in React and TypeScript, featuring a clean UI and smooth user interactions.",
    technology: ["REACT", "CSS", "TYPESCRIPT"],
  },
  {
    github: "https://github.com/Raja-Simform/Typescript-calculator",
    live: "https://cozy-tartufo-07cb76.netlify.app/",
    title: "Scientific-Calculator",
    desc: "A fully functional scientific calculator built with TypeScript, supporting advanced mathematical operations and a user-friendly interface.",
    technology: ["HTML", "CSS", "TYPESCRIPT"],
  },
  {
    github: "https://github.com/Raja-Simform/Investment-calculator",
    live: "https://deploy-preview-2--bright-entremet-ad2dc4.netlify.app/",
    title: "InvestmentCalculator",
    desc: "An investment calculator app developed with React and TypeScript that helps users estimate returns based on different investment parameters.",
    technology: ["REACT", "CSS", "TYPESCRIPT"],
  },
  {
    github: "https://github.com/Raja-Simform/practical-test",
    live: "https://practical-test-nbk6cuz76-raja-jhas-projects.vercel.app/",
    title: "Quizz Game",
    desc: "An engaging quiz game built with TypeScript, featuring multiple-choice questions and real-time score tracking.",
    technology: ["HTML", "CSS", "TYPESCRIPT"],
  },
  {
    github: "https://github.com/Raja-Simform/SnackBarComponent",
    live: "https://snack-bar-component.vercel.app/",
    title: "Snack Bar Componet",
    desc: "A reusable Snack Bar component created with React, Styled Components, and TypeScript to display notifications elegantly.",
    technology: ["REACT", "STYLED COMPONENT", "TYPESCRIPT"],
  },
];
